### PR TITLE
Modals Generator

### PR DESCRIPTION
**Pull request by Jeremy-Walton**
## Task

Fix modal issues noted in #100 

## Why?

The modals generator was not pointing to the correct files and the template was not up to date.
Since Optics provides the modal as a full component now instead of an addon, these needed to be updated.

There might be a future PR to start using the `dialog` element, but there is further discussion needed on it.

## What Changed

* [X] Clean up injected styles
* [X] Use Optics template for modal

### CODE REVIEW

**Review by OutlawAndy — APPROVED** [review]
Thanks @Jeremy-Walton! 👍

**Comment by Jeremy-Walton** [comment]
@OutlawAndy I realized there is more work to be done getting the Confirm Dialog updated to use the latest from Optics as well. https://docs.optics.rolemodel.design/?path=/docs/components-confirm-dialog--docs

Would love to pair with you on that as well. Maybe next week some time.

**Comment by Braden-077** [comment]
@Jeremy-Walton What's the status on this PR?

**Comment by Jeremy-Walton** [comment]
@Braden-077 Would like to see some feedback from @calebwoods on https://trello.com/c/llL8ASEM/85-migrate-to-the-dialog-element first but hadn't gotten a chance to bring it up with him.

**Pull request merged**
